version: '3.8'

services:

  mailserver:
    image: mailserver/docker-mailserver:12.1
    container_name: mailserver
    hostname: ${HOSTNAME}
    ports:
      - "25:25"     # ESMTP Explicit TLS (transfer)
      - "465:465"   # ESMTP Implicit TLS (submission)
      - "587:587"   # ESMTP Explicit TLS (submission)
      - "110:110"   # POP3 Explicit TLS (retrieval)
      - "995:995"   # POP3 Implicit TLS (retrieval)
      - "143:143"   # IMAP4 Explicit TLS (retrieval)
      - "993:993"   # IMAP4 Implicit TLS (retrieval)
    volumes:
      - ./volumes/dms/mail-data/:/var/mail/
      - ./volumes/dms/mail-state/:/var/mail-state/
      - ./volumes/dms/mail-logs/:/var/log/mail/
      - ./volumes/dms/config/:/tmp/docker-mailserver/
      - ./volumes/certbot/certs/:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_POP3=${ENABLE_POP3}
      - ENABLE_RSPAMD=${ENABLE_RSPAMD}
      - ENABLE_CLAMAV=${ENABLE_CLAMAV}
      - ENABLE_FAIL2BAN=${ENABLE_FAIL2BAN}
      - ENABLE_SPAMASSASSIN=${ENABLE_SPAMASSASSIN}
      - SSL_TYPE=${SSL_TYPE}
      - SPOOF_PROTECTION=${SPOOF_PROTECTION}
      - POSTFIX_MAILBOX_SIZE_LIMIT=${POSTFIX_MAILBOX_SIZE_LIMIT}
      - POSTFIX_MESSAGE_SIZE_LIMIT=${POSTFIX_MESSAGE_SIZE_LIMIT}
      - POSTMASTER_ADDRESS=${POSTMASTER_ADDRESS}
      - SA_SPAM_SUBJECT=${SA_SPAM_SUBJECT}
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always

  postgres:
    image: postgres:15.4
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    restart: always

  roundcube:
    image: roundcube/roundcubemail:1.6.2-fpm-alpine
    container_name: roundcube
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://${HOSTNAME}
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://${HOSTNAME}
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=${DB_DATABASE}
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=postgres
      - ROUNDCUBEMAIL_DB_PORT=5432
      - ROUNDCUBEMAIL_DB_USER=${DB_USER}
      - ROUNDCUBEMAIL_DB_PASSWORD=${DB_PASSWORD}
      - ROUNDCUBEMAIL_DB_NAME=${DB_DATABASE}
    restart: always
    depends_on:
      - mailserver
      - postgres

  nginx:
    image: nginx:1.25.2
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/certbot/certs/:/etc/letsencrypt/
    restart: always
    depends_on:
      - roundcube
